version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    links:
      - 'db:db'
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.4
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=Bao123456.'
      - 'POSTGRES_DB=timesheet-fpt'
