version: '3'
services:
  app:
    # build: .
    image: 786630211257.dkr.ecr.ap-northeast-1.amazonaws.com/timesheet-ft:latest
    ports:
      - '3000:3000'
    links:
      - 'db:db'
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.4
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=Bao123456.'
      - 'POSTGRES_DB=timesheet-fpt'
