export enum RequestTypeCode {
  'MISSING_IN' = 'MISSING_IN',
  'MISSING_OUT' = 'MISSING_OUT',
  'MORNING_ABSENT' = 'MORNING_ABSENT',
  'AFTERNOON_ABSENT' = 'AFTERNOON_ABSENT',
  'FULL_DAY_ABSENT' = 'FULL_DAY_ABSENT',
  'REMOTE_WORKING' = 'REMOTE_WORKING',
}
